### ISSUE TITLE
No binary extension?

### ISSUE THREAD

**Issue by salexmatei** [agfline/wavfix#8]
There is no file extension for your downloads. I would like to use your program but I have no idea how to make use of the binary. Compiling the source proves to be even more frustrating for a non-programming savvy person. Do I have to give the binary an extension or what exactly do I do with it??

**Comment by agfline** [comment]
Hi, you have all the binary files in [release](https://github.com/agfline/wavfix/releases/tag/v0.1) for Mac, Windows and Linux. There is no extension for mac and linux binaries.

Wavfix is a command line tool, meaning you have to first open your OS terminal / console / cmd, then either go to the directory that contains the wavfix binary `cd /path/to/wavfix` and then run it `./wavfix-0.1-mac32`, or run wavfix directly using `/path/to/wavfix/wavfix-0.1-mac32`.

**Comment by salexmatei** [comment]
ok, thanks for the quick reply!
